name: Teste CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: LOGIN
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build 
      run: docker build . --file Dockerfile --tag time-zone:lateste
    - name: Checkout
      uses: actions/checkout@v3



#name: Teste CI

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Login to Docker Hub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKER_HUB_USERNAME }}
#        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Build and push
#      run: docker build . --file Dockerfile --tag time-zone:latest
    
      
