name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/time-zone
          
          
#name: Teste CI

#on:
  #push:
    #branches: [ "master" ]
  #pull_request:
    #branches: [ "master" ]

#jobs:
  #login:
    #runs-on: ubuntu-latest
    #steps:
    #- name: LOGIN
      #uses: docker/login-action@v2
      #with:
        #username: ${{ secrets.DOCKER_HUB_USERNAME }}
        #password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #build:
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v3
    #- name: Build 
      #run:  docker build --file Dockerfile -t 85devs/time-zone .
    #- name: Checkout
      #uses: actions/checkout@v3



    
      
